<a href="https://colab.research.google.com/github/lawrenceemenike/Transformers-for-NLP/blob/main/Transformers_for_NLP_Chapter_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.special import softmax

In [2]:
print("Step 1: Input  3 inputs, d_model=4")
x = np.array([[1.0, 0.0, 1.0, 0.0],
              [0.0, 2.0, 0.0, 2.0],
              [1.0, 1.0, 1.0, 1.0]])

print(x)

Step 1: Input  3 inputs, d_model=4
[[1. 0. 1. 0.]
 [0. 2. 0. 2.]
 [1. 1. 1. 1.]]


In [3]:
print("Step 2: weights 3 dimensions x d_model=4")
print("w_query")
w_query = np.array([[1, 0, 1],
                   [1, 0, 0],
                    [0, 0, 1],
                    [0, 1, 1]])
print(w_query)

Step 2: weights 3 dimensions x d_model=4
w_query
[[1 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 1]]


In [13]:
print("w_key")
w_key = np.array([[0, 0, 1],
                  [1, 1, 0],
                  [0, 1, 0],
                  [1, 1, 0]])
print(w_key)

w_key
[[0 0 1]
 [1 1 0]
 [0 1 0]
 [1 1 0]]


In [8]:
print('w_value')
w_value = np.array([[0, 2, 0],
                    [0, 3, 0],
                    [1, 0, 3],
                    [1, 1, 0]])
print(w_value)

w_value
[[0 2 0]
 [0 3 0]
 [1 0 3]
 [1 1 0]]


In [9]:
print("Step 3: Matrix multiplication to obtain Q, k, V")
print(" Query: x * w_query")
Q = np.matmul(x,w_query)
print(Q)

Step 3: Matrix multiplication to obtain Q, k, V
 Query: x * w_query
[[1. 0. 2.]
 [2. 2. 2.]
 [2. 1. 3.]]


In [14]:
print("key: x * w_key")
k=np.matmul(x,w_key)
print(k)

key: x * w_key
[[0. 1. 1.]
 [4. 4. 0.]
 [2. 3. 1.]]


In [15]:
print("value: x * w_value")
v=np.matmul(x,w_value)
print(v)

value: x * w_value
[[1. 2. 3.]
 [2. 8. 0.]
 [2. 6. 3.]]


In [17]:
print("step 4: Scaled Attention Scores")
k_d=1 # square root of k_d=3 rounded down to 1 for this example
attention_scores = (Q @ k.transpose())/k_d
print(attention_scores)

step 4: Scaled Attention Scores
[[ 2.  4.  4.]
 [ 4. 16. 12.]
 [ 4. 12. 10.]]


In [18]:
print("Step 5: Scaled softmax attention_scores for each vector")
attention_scores[0]=softmax(attention_scores[0])
attention_scores[1]=softmax(attention_scores[1])
attention_scores[2]=softmax(attention_scores[2])
print(attention_scores[0])
print(attention_scores[1])
print(attention_scores[2])

Step 5: Scaled softmax attention_scores for each vector
[0.06337894 0.46831053 0.46831053]
[6.03366485e-06 9.82007865e-01 1.79861014e-02]
[2.95387223e-04 8.80536902e-01 1.19167711e-01]


In [19]:
print("Step 6: attention value obtained by score1/k_d * v")
print(v[0])
print(v[1])
print(v[2])
print("Attention 1")
attention1 = attention_scores[0].reshape(-1, 1)
attention1 = attention_scores[0][0]*v[0]

print("Attention 2")
attention2 = attention_scores[0][1]*v[1]
attention2=attention_scores[0][1]*v[1]
print(attention2)

print("attention 3")
attention3 = attention_scores[0][2]*v[2]
print(attention3)


Step 6: attention value obtained by score1/k_d * v
[1. 2. 3.]
[2. 8. 0.]
[2. 6. 3.]
Attention 1
Attention 2
[0.93662106 3.74648425 0.        ]
attention 3
[0.93662106 2.80986319 1.40493159]


In [20]:
print("Step 7: summed the results to create the first line of the output matrix")
attention_input1=attention1+attention2+attention3
print(attention_input1)

Step 7: summed the results to create the first line of the output matrix
[1.93662106 6.68310531 1.59506841]


In [21]:
print("Step 8: Step 1 to 7 for inputs 1 to 3")
# Wwe assume we have 3 results with learned weights and also assume we are implementing the original Transfomer paper. we will have 3 results of 64 dimensions each
attention_head1=np.random.random((3, 64))
print(attention_head1)

Step 8: Step 1 to 7 for inputs 1 to 3
[[6.65634620e-01 2.98484911e-01 2.13635072e-01 5.87705856e-01
  5.93561498e-01 7.31227750e-01 1.42040131e-01 3.20935599e-01
  7.47038386e-01 8.74160181e-01 6.90196689e-01 3.20403285e-01
  4.76562085e-01 8.78017596e-01 4.46385295e-01 4.18043024e-01
  2.48330405e-01 3.78111370e-01 1.86945256e-01 5.23142372e-01
  1.17537060e-02 8.38221158e-01 6.59938474e-01 6.51682451e-01
  6.18360574e-01 8.09242344e-01 9.97209383e-01 7.21418231e-01
  5.04651500e-01 2.95689226e-01 1.15108670e-01 5.21047765e-01
  6.08157621e-02 3.31099436e-01 3.98979673e-01 1.60332887e-01
  1.32472079e-01 9.15913592e-01 2.94071579e-02 4.87431879e-01
  5.91190730e-01 8.28719296e-01 1.10555997e-01 4.84599965e-01
  6.67625178e-01 1.87146063e-01 1.71251197e-01 2.24514284e-01
  7.24753394e-01 2.74983019e-01 3.22658210e-01 7.03801460e-01
  6.59175189e-01 3.79487039e-01 3.23711228e-01 9.70324916e-01
  4.43512141e-01 1.80236480e-01 4.84666419e-01 3.16105756e-01
  2.04035433e-01 7.89268916e-02 

In [24]:
print("Step 9: Wwe assume have trained the 8 heads of the attention sublayer")
z0h1=np.random.random((3, 64))
z1h2=np.random.random((3,64))
z2h3=np.random.random((3, 64))
z3h4=np.random.random((3,64))
z4h5=np.random.random((3, 64))
z5h6=np.random.random((3,64))
z6h7=np.random.random((3, 64))
z7h8=np.random.random((3,64))
print("shape of one head", z0h1.shape, "dimension of 8 heads", 64*8)

Step 9: Wwe assume have trained the 8 heads of the attention sublayer
shape of one head (3, 64) dimension of 8 heads 512


In [25]:
print("Step 10: Concantenation of heads 1 to 8 to obtain the original 8x64=512 output dimension of the model")
output_attention=np.hstack((z0h1, z1h2,z2h3,z3h4,z4h5,z5h6, z6h7, z7h8))
print(output_attention)

Step 10: Concantenation of heads 1 to 8 to obtain the original 8x64=512 output dimension of the model
[[0.06153983 0.79584684 0.91439377 ... 0.40356964 0.66354238 0.71816946]
 [0.4405419  0.918761   0.9772307  ... 0.00898934 0.67232367 0.88206427]
 [0.23488868 0.93517597 0.13842944 ... 0.73114349 0.29119771 0.1979142 ]]
